### ISSUE TITLE
Amazing project, congratulations!

### ISSUE THREAD

**Issue by frederikhors** [fwojciec/gqlgen-sqlc-example#1]
Amazing project!

Will you write other articles for your fans?

😄

**Comment by fwojciec** [comment]
Thanks Fredrik for your kind words :)

Definitely, I already have some code written for the next part in the tutorial (authentication) but I haven't been able to find a free weekend to actually turn it into a post.  I've just started a new job, so things are more busy than usual, but I'll get to it eventually.

I'll close the issue for now, please feel free to re-open if I'm taking too long! :)

**Comment by fr3fou** [comment]
When will the auth part be released? I was really impressed by the articles btw!
